project_name: notify

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - freebsd_amd64
      - freebsd_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm_7
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - sudo chown 0:0 '{{ .Path }}'

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-next"
